language: node_js

node_js:
- node
cache:
  directories:
  - node_modules

env:
  global:
  - secure: ZUDDZx4iuyKU1YhVPzhRmWddByioviTpYWvp2Wfe0N2xcli9DdbvJi0eUrQWZxOQspjEHZo6cG/EyL1ILfbjMaIPRQFRwmhMhqjVcZ0p7QcjISM394SQdYzO96o4LNUhvigiznN6+1RVhjkC0Z1t8bKt5hpyA/RjawAhS4Iu1A9cyWnU9U3Stb9ndeMvS4v4SLVAO1LCCI2UkJbXGTb6RQ2eMMKOv+bQytpsOyub4XNRDbaAxnuWGog7jyaRrea1OSrz5yMCQa1sf7HZvtnlkvfloOh2buOJoxqx186h+UC6FjLPKS399WD7S3Itl4OyicEKOnE0HY87BVSfY9I9XqS0d44XL7kVJd+EGcCLKu6JMAN+rP/TAXjqX0yD5wEOZ41oLl6HZQZB13NH0Ktu/n5i+Bh8x0mdMsVonJ+Znqf3POcYLUwX2RXEskhDCrqYTdH4EUZA3Ot1BhoX/iz6C+f1dc/F3SW9CMIDxsbkHJ1pYY5mrXuQHElXOvA5+yD62TWdjjnB/cZou4iXAMUGvtyxbx3EEL0EXcBtmEW+ZIyHmcWkTckJARP35qFsIcvUZ56NCMyWvL3PGTGCA69tMXSnPVQUEGYTQbYLcTD1CC87BiKlDq8fNzWYLET6NGEXRiiswndgebzj3AwM9GenGX1tcbUSgn3W+ejNU0MyX0s=
  - secure: YU1UvyLGoN5WcE89/N8fsVmTxCgORZRK6uXGJudiYB46uMxnPdhMr9mZpGWjISVfSd6jkQdKF0faeHcwUffVLK9tcATOzYuQYcSgVWr/dM2aixOfbBAJA34c1OAJ7YufCk0XUGjBKvmivIkPA3Jv1TqxxtHzEeSl3pogNu6rjamKMM/xfj3ZS9mmOobnd5f/goR5/dhg0PTpRWvuhFnxIFnfI8ApoqAwYkxJbCjlf2/U23UnVu7n5FZZQ6fMBGnrbKLKWMhQ1N14FsOWKJeRgeGXRI0H4WYq6hsTxsWmI0P3dy9HnVk32N/wJOHLQtAKzLXhSz8SV1qHcblRZqTLf+KxyVksOqjRsUesbAkSQgJVb8MuFJdlZMIW8Dd0562+lrC+732lBjZUqkACfSmP58toYO5OhfK5lCEiCg43mief4hP1U1MwUJSmH6Qn1L6thRYXgVBJ8QuTmIG2x5mqglLkJBzJuFGlKwjYIdQMH1EPzsqtYA/kZw1j/9/HvzvYXLmrbhTlUTFF3Kzv4qVeZ3vDjAwcYzm8iuu6ULbnh+sJUg1YkgMv9btp+idcIkS9iTh7RQQh1J2VI9tbFJZhyK3aL0rivOQlESshR2pPZai2AwHD9PzWbDbfdVj94/7AOF6NHxLcR+QiCMSkei2dXIe0tNSJzJxaNHqpNkWYu+4=
  - UNIQUE_PREFIX=youruniqueprefix
  - EXPORT_IMPORT_BUCKET=$UNIQUE_PREFIX-export-import-bucket
  - PRIMARY_REGION=us-east-1
  - SUPPORTED_REGIONS=us-east-1,us-west-2,ap-southeast-2
  - secure: Rac4p6moDPN0xXUEmyuBU71SEp9RwMeMb9rc5+oDQWGhci6EcEF7uqDM4gLzMkCqNOU0tTtAnAaGzDLjJItYVng58MCAn3z39LD1cRomonmbdkVnjk3+XmBY22/a38iZS6k2tPNdzM7iMiB6lO3Bg2cKJ1MQRtWOuk7B40rLB/avNdEQd6nktrlS1yH97ugcNArZD34nQZrdoTAkf/Lj185CJV4gwIyts+sG0VjiDYUsT4V3ZY3fDAWESKFx1atmL7lnHw5oRrynsCnMCFVc9QnYjHhdxDOwCfniGB5UbK5syDuJDR3a8D1nYq36xLtJfRrbVB9HtKlR8CDo4wOY17mNN+lnXuw/ygSKlyP7EQf808gd0BKhGVYVqvEoigBPId0IfMNW+N4whCq0duW+QkcLGAW6P0XYm7RU7sG3iBRT/Od6QhsdsDJF8N9JUJY5XKzsRcNFkjj3Ti7hbE6lUenICDILalDOptneFIo0Tx+WLXrGW6EPMA+oDUlQMz3EzomShHx9AMRkowSyPYIr6SjMIk9zCzaa5uLVGhnXe6/0wnlXRwaPsLIi/K/F+qVLj2OGZMk6dYgmxfF7MjFmDt+6+5/3gq0OexfrbMows2vBZ9VgD6oxMqOwFUF+brqSPFTYiVlTKv9Qs/5OMj5Jplpel23ctUXyxKFW8IESnko=
  - secure: PwqswWTXjYtOMtiUsnJhoRriefQy7QieJzryjTr4UIDulm/SndgYMPMBMUDuNJcrDVyv26gyCXWfqBrGIVHtVsWaQtBY8zYRJF8y6MxX1ZwHemMJiCKXPUxAG2IajL/+l8SnUN+8n7Q2ZauE9HVIApMShNWNBaeXHj+jZqhe4SciHH8zObZl1JolxYJ7fciagoY6Qs4Rr2PYghqeyJhkCJn69XLY8EMvlGBLc2bbc8J5sNLpWoSkYAxM4EoBA2CeBjmiXf8IMJW3ZzSi+Dy+3+UTnK3IE0P0uUS7Xi+AJfFtqd5f7CSylL7EcejskJmy0QxKd7KYP7HpHvA/ATvRd/t0h3oxnKV+AKeu5EFVLZV+xYixQPSjs6GbxiqBN9WsSsFUUHTyDz1Ze2Ev5IfLjAdne5/J0A2Pythb7qy9Mlh6e7A24fQJFMKuusSMCBj64n3tKAGGww+9jZgkvARzE42Dxcvc+jgaJKRuWrCDS9uT8izv4U2c9JQ29axSXqeMk9jKVdDYAmEt1HVrTpFUYa9ltc97bjS8UDRjKG+VJkKem5m2+WVnGUSkEltQT8ein76c/r27ySDgt3jxLT4Ilpp62vs3HHpHgmB57/mpdPtnLzRCv7T5TQQpMDMCXeUZAuCtGWYikmcl6p0L2St5PpDLsk2q3GMX3gx52+dsb0I=

before_install:
- find . -name "*.sh" -print0 | xargs -0 chmod +x
- pip install --user awscli

install:
- npm install -g serverless

script:
- "./scripts/ecr_credentials.sh"
- "./scripts/setup.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION $SUPPORTED_REGIONS"
- "./scripts/provision_slave_account_role.sh $UNIQUE_PREFIX $PRIMARY_REGION"
- "./scripts/deploy_primary_region.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION"
- "./scripts/deploy_supported_regions.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION $SUPPORTED_REGIONS"
- "./scripts/connect_primary_supported.sh $UNIQUE_PREFIX $PRIMARY_REGION $SUPPORTED_REGIONS"
