language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_install:
    - npm install -g serverless
# dist: xenial
#   addons:
#     snaps:
#     - name: aws-cli
#       confinement: classic # or devmode
#       channel: latest/edge # will be passed to --channel flag

env:
  global:
  - secure: ZUDDZx4iuyKU1YhVPzhRmWddByioviTpYWvp2Wfe0N2xcli9DdbvJi0eUrQWZxOQspjEHZo6cG/EyL1ILfbjMaIPRQFRwmhMhqjVcZ0p7QcjISM394SQdYzO96o4LNUhvigiznN6+1RVhjkC0Z1t8bKt5hpyA/RjawAhS4Iu1A9cyWnU9U3Stb9ndeMvS4v4SLVAO1LCCI2UkJbXGTb6RQ2eMMKOv+bQytpsOyub4XNRDbaAxnuWGog7jyaRrea1OSrz5yMCQa1sf7HZvtnlkvfloOh2buOJoxqx186h+UC6FjLPKS399WD7S3Itl4OyicEKOnE0HY87BVSfY9I9XqS0d44XL7kVJd+EGcCLKu6JMAN+rP/TAXjqX0yD5wEOZ41oLl6HZQZB13NH0Ktu/n5i+Bh8x0mdMsVonJ+Znqf3POcYLUwX2RXEskhDCrqYTdH4EUZA3Ot1BhoX/iz6C+f1dc/F3SW9CMIDxsbkHJ1pYY5mrXuQHElXOvA5+yD62TWdjjnB/cZou4iXAMUGvtyxbx3EEL0EXcBtmEW+ZIyHmcWkTckJARP35qFsIcvUZ56NCMyWvL3PGTGCA69tMXSnPVQUEGYTQbYLcTD1CC87BiKlDq8fNzWYLET6NGEXRiiswndgebzj3AwM9GenGX1tcbUSgn3W+ejNU0MyX0s=
  - secure: YU1UvyLGoN5WcE89/N8fsVmTxCgORZRK6uXGJudiYB46uMxnPdhMr9mZpGWjISVfSd6jkQdKF0faeHcwUffVLK9tcATOzYuQYcSgVWr/dM2aixOfbBAJA34c1OAJ7YufCk0XUGjBKvmivIkPA3Jv1TqxxtHzEeSl3pogNu6rjamKMM/xfj3ZS9mmOobnd5f/goR5/dhg0PTpRWvuhFnxIFnfI8ApoqAwYkxJbCjlf2/U23UnVu7n5FZZQ6fMBGnrbKLKWMhQ1N14FsOWKJeRgeGXRI0H4WYq6hsTxsWmI0P3dy9HnVk32N/wJOHLQtAKzLXhSz8SV1qHcblRZqTLf+KxyVksOqjRsUesbAkSQgJVb8MuFJdlZMIW8Dd0562+lrC+732lBjZUqkACfSmP58toYO5OhfK5lCEiCg43mief4hP1U1MwUJSmH6Qn1L6thRYXgVBJ8QuTmIG2x5mqglLkJBzJuFGlKwjYIdQMH1EPzsqtYA/kZw1j/9/HvzvYXLmrbhTlUTFF3Kzv4qVeZ3vDjAwcYzm8iuu6ULbnh+sJUg1YkgMv9btp+idcIkS9iTh7RQQh1J2VI9tbFJZhyK3aL0rivOQlESshR2pPZai2AwHD9PzWbDbfdVj94/7AOF6NHxLcR+QiCMSkei2dXIe0tNSJzJxaNHqpNkWYu+4=
  - UNIQUE_PREFIX=youruniqueprefix
  - EXPORT_IMPORT_BUCKET=$UNIQUE_PREFIX-export-import-bucket
  - PRIMARY_REGION=us-east-1
  - SUPPORTED_REGIONS=(us-east-1 us-west-2 ap-southeast-2)

before_install:
- find . -name "*.sh" -print0 | xargs -0 chmod +x
- pip install --user awscli

script:
- ./scripts/ecr_credentials.sh
- ./scripts/setup.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION
- ./scripts/deploy_primary.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION
- ./scripts/deploy_supported.sh $UNIQUE_PREFIX $EXPORT_IMPORT_BUCKET $PRIMARY_REGION $SUPPORTED_REGIONS
- ./scripts/connect.sh $UNIQUE_PREFIX $PRIMARY_REGION $SUPPORTED_REGIONS

# jobs:
#   include:
#   - stage: setup files
#     script: echo one | tee > ~/$TRAVIS_BUILD_NUMBER/one
#   - stage: setup files
#     script: echo two | tee > ~/$TRAVIS_BUILD_NUMBER/two
#   - stage: use shared files
#     script:
#     - cat ~/$TRAVIS_BUILD_NUMBER/*
#     after_success:
#     - aws s3 rm --recursive s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
# after_success:
# - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
